### ISSUE TITLE
Fehler bei Nutzung von -dname in aseag-api.py 

### ISSUE THREAD

**Issue by claell** [acmurmeltier69/Alexa-Busauskunft#11]
Ich habe gerade mal kurz die aseag-api.py ausprobiert.
Bei `python aseag_api.py -oname 'Ponttor' -dname 'Westbahnhof'`
kommt:
```
in main
  Debug (5): got API request 
{u'currentServerTimeInUnixEpochMillis': 1488791206195, u'resultCount': 1, u'type': u'LocationResults', u'resultList': [{u'latitude': 50.7808611, u'stopPointName': u'Ponttor', u'type': u'StopPoint', u'stopPointId': u'100005', u'longitude': 6.0779722}], u'maxResults': 5}
--------------
  Debug (3): Found a single match for 'Ponttor': 100005 : Ponttor
  Debug (5): got API request 
{u'currentServerTimeInUnixEpochMillis': 1488791206226, u'resultCount': 1, u'type': u'LocationResults', u'resultList': [{u'latitude': 50.7805372, u'stopPointName': u'Westbahnhof', u'type': u'StopPoint', u'stopPointId': u'100641', u'longitude': 6.0719672}], u'maxResults': 5}
--------------
  Debug (3): Found a single match for 'Westbahnhof': 100641 : Westbahnhof
Traceback (most recent call last):
  File "aseag_api.py", line 548, in <module>
    main()
  File "aseag_api.py", line 495, in main
    if len(destination_id) != 1: 
UnboundLocalError: local variable 'destination_id' referenced before assignment
```

Wollte ich nur melden, falls das Einbauen der Kommandozeilenoptionen was kaputt gemacht haben sollte.

**Comment by acmurmeltier69** [comment]
oops, da hat ein s gefehlt.  sollte len(destination_ids) sein
die variable heisst jetzt destination_id_list das ist sauberer
